name: oob-migrate
config:
  webroot: .
services:
  database:
    type: mongo
    portforward: 27017
  appserver:
    type: node:10
    command: yarn start
    portforward:
     - 3000
     - 9229
    overrides:
      ports:
        - 3000:3000
        - 9229:9229
